language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: fotkKkk8P0GvHwaxWUBZkXpKKE5P1YQqXipjACwwaBpRSCGq+OmyTuoDoVG1XSdNg9a0mGLgTdd1V7Io0sU0zu1bSpd6FgglXwMC4rQV++WRHwE2si2JErf7MHcum0t18s6Ex1Bsw19Io4XBqrXblHFKIFPiuy55+mYU/I0VAwPgirTl/Sw7jECQzDQDJ+w3YEGSNl8K56T9s8JFONBxQmZtq49uNhnx8jmJb2wsqzDiKy9KCIjOWQdXAHgNMhEOe6/DNCWuo9Ssoz25RhZ5fE7ENYxUi/ZlAGb/U57ByQiBFqfU8gH0ycQ08xYnOw/Je0WladYD1phXkiyD3SmGGjgQpRN7uYHp3xlmIoGYQ2EVdD0uxtHEejPX/v4TuxtS4DvHJTOlJ/gHgfYN6gEBTCJP5m9zRqHaENe/Oa7qq+1BPqRUSSHNgAI4jdkpJVKc/l5a3M5Iq91eiWvXVDJln6MSXLkvWLel110VEGcaJSXJT3cF+CswED2QfW6x9L4ZPA7rt2KUjnZLKjfG8zDChGyQuGvmyC9jZbVW3ZNMUAikkfhmNLUTftLG7dmE0MiP5oB3IppqdbvxlCpSI02DMJk+vixkdi58Td55RySTC4YpYRXYHS19aL9zVtv+dhR7VaEXjVDCI9y1SfvnVZcfHOZOG11U8CpGzfgL0KxrgoE=
  app: jf-runtime